[versions]
# libraries
assertj = "3.27.7"
buf = "1.64.0"
junit = "4.13.2"

# plugins
kotlin = "2.1.0"
changelog = "2.5.0"
intelliJPlatform = "2.11.0"
qodana = "2025.3.1"
kover = "0.9.5"
osdetector = "1.7.3"
spotless = "8.2.1"

[libraries]
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
buf = { module = "build.buf:buf", version.ref = "buf" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
osdetector = { id = "com.google.osdetector", version.ref = "osdetector" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
